title: Awesome Git Notes
description: Awsome notes about Git
theme: just-the-docs

url: https://OlivierRRC.github.io/Group-2-Git-Site

aux_links:
  Template Repository: https://github.com/OlivierRRC/Group-2-Git-Site
