title: Awesome Git Notes
description: Awsome notes about Git
theme: just-the-docs

url: https://OlivierRRC.github.io/Just-The-Docs-Template

aux_links:
  Template Repository: https://github.com/OlivierRRC/Just-The-Docs-Template
